export enum GatewayPermissions {

    ADMINISTRADOR = "ADMINISTRADOR",
    MANAGE_USERS = "MANAGE_USERS",
    MANAGE_PACKAGES = "MANAGE_PACKAGES",
    VIEW_STATS = "VIEW_STATS",
    MANAGE_BOTS = "MANAGE_BOTS",
    SET_PASSWORD = "SET_PASSWORD"

}